In [2]:
#numpy 
import numpy as np

In [3]:
#cria uma matriz unidimensional
mt = np.array([12,34,18,10])
print(mt)
print(type(mt)) #mostra o tipo array do numpy

[12 34 18 10]
<class 'numpy.ndarray'>


In [5]:
#criar o array com um tipo especifico

mtfloat = np.array([1,2,3], dtype = np.float64)
print(mtfloat)
print(type(mtfloat))

mtint = np.array([1,2,3], dtype = np.int32)
print(mtint)
print(type(mtint))

#mudando o tipo do array
mtnew = mtint.astype(np.float64)
print(mtnew)
print(type(mtnew))


[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>
[1. 2. 3.]
<class 'numpy.ndarray'>


In [11]:
#criar arrays vazioa tipificados
#empty significa que não foi inicializado, não que são vazios
vazio= np.empty([3,2], dtype = int)
print(vazio)
print("---------------")

#cria matriz 4x3 com valores zero
zeros = np.zeros([4,3])
print(zeros)
print(type(zeros))
print("-------------------")

#com valores igual a um
um = np.ones([5,7])
print(um)
print(type(um))
print("----------------")

#cria matriz quadrada com digonal principal com valores 1 e outros valores zero
diagonal = np.eye(10)
print(diagonal)
print(type(diagonal))



[[         0 1072693248]
 [         0 1073741824]
 [         0 1074266112]]
---------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>
-------------------
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
<class 'numpy.ndarray'>
----------------
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
<class 'numpy.ndarray'>


In [13]:
#valores aleatorios entre zero e um
ale = np.random.random((5))
print(ale)
print(type(ale))

#valores aleatórios distr. normal contendo negativos
ale2 = np.random.randn((5))
print(ale2)
print(type(ale2))

#valores aleatórios 3 x 4 
ale3 = (10*np.random.random((3,4)))
print(ale3)

[0.04196639 0.04130159 0.76146645 0.88780008 0.33515854]
<class 'numpy.ndarray'>
[-1.65433567 -0.99907749  0.61415922 -0.71351671  1.02047833]
<class 'numpy.ndarray'>
[[3.38948393 1.78373515 7.22491105 5.45559693]
 [3.5423846  1.58480941 9.23994652 3.31275451]
 [6.10813993 4.54059261 2.51167168 3.22392478]]


In [17]:
#unique remove repetições 
k = np.array([12,12,12,13,13,14,15,16,16,17,18,19,20,20])
k = np.unique(j)
print(k)

[12 13 14 15 16 17 18 19 20]


In [18]:
#Funções Matematicas
#mostra o maior valor da matriz k
print(k.max())
#mostra o menor valor da matriz k
print(k.min())
#mostra a soma dos calores da matriz k
print(k.sum())
#mostra o valor medio dis valores da matriz k
print(k.mean())
#mostra o valor do desvio padrão dos valores da matriz k
print(k.std())


20
12
144
16.0
2.581988897471611


In [ ]:
#Expressões logicas
#usando where
#criando matriz com valores aleatórios positivos e negativos
v = np.random.randn(4,4)
print(v)

#criando matriz com valores booleanos baseado no array v
x = (v > 0)
print(x)

#criando matriz com valores -1 e 1 baseado nos valores do array x
z = np.where(x > 0, 1, -1)
